apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: helloworld
          image: 297797860062.dkr.ecr.eu-central-1.amazonaws.com/myapp:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: regcred
